name: QA Automation Master Suite

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test-ui-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-node@v4.1.0
        with: { node-version: 18 }
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test
      - uses: actions/upload-artifact@v4.4.0
        if: always()
        with:
          name: playwright-report
          path: playwright-report/

  test-api-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-node@v4.1.0
        with: { node-version: 18 }
      - run: npm install -g newman newman-reporter-htmlextra
      - run: newman run tests/api/restful-booker.json -r cli,htmlextra --reporter-htmlextra-export api-report.html
      - uses: actions/upload-artifact@v4.4.0
        if: always()
        with:
          name: newman-report
          path: api-report.html

  test-perf-k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run K6 Load Test
        run: k6 run tests/performance/load_test.js
      - uses: actions/upload-artifact@v4.4.0
        if: always()
        with:
          name: k6-report
          path: tests/performance/
